/**
 * Created by ijoy on 16-7-8.
 */
import React from 'react'

import {
    View,
    Text,
    StyleSheet
} from 'react-native'
import {MKSwitch,MKColor} from 'react-native-material-kit'
var PushNotification = require('react-native-push-notification');

export default class Setting extends React.Component{
    sendNotify(){
        PushNotification.localNotification({
            /* Android Only Properties */
            id: 0, // (optional) default: Autogenerated Unique ID
            title: "无线应用辅助管理系统", // (optional)
            ticker: "无线应用辅助管理系统", // (optional)
            autoCancel: true,
        largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
            smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
            bigText: "你已经设置手机消息提醒", // (optional) default: "message" prop
            subText: "设置消息提醒", // (optional) default: none
            number: 10, // (optional) default: none (Cannot be zero)
            color: "red", // (optional) default: system default

            /* iOS and Android properties */
            message: "My Notification Message" // (required)
    });
    }
    render(){
        return(
          <View>
              <View style={styles.lineItem}>
                  <View style={{flex:1,justifyContent:'center'}}>
                      <Text style={styles.title}>系统消息提醒</Text>
                      </View>

                  <MKSwitch style={{width:100}}
                            trackSize={30}
                            trackLength={52}
                            onColor="rgba(255,152,0,.3)"
                            thumbOnColor={MKColor.Orange}
                            rippleColor="rgba(255,152,0,.2)"
                            onPress={() => console.log('orange switch pressed')}
                            onCheckedChange={()=>this.sendNotify()}
                  />
              </View>
          </View>
        );
    }
}

const styles=StyleSheet.create({
    lineItem:{
        margin:5,
        paddingBottom:10,
        borderBottomWidth:1,
        borderColor:'green',
        flexDirection:'row',

    },
    title:{
        marginBottom:5,
        fontSize:20,
    }
});